eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8762/eureka/

spring:
  application:
    name: authentication_service
  datasource:
    url: jdbc:mysql://mysql-users:3306/users_db
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

logging:
  level:
    root: DEBUG


server:
  port: 9997

